const abi = [{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"customer","type":"address"},{"indexed":false,"internalType":"uint256","name":"balance","type":"uint256"}],"name":"Deposit","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"customer","type":"address"}],"name":"Ended_contract","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"customer","type":"address"},{"indexed":false,"internalType":"bytes32","name":"filehash","type":"bytes32"},{"indexed":false,"internalType":"uint256","name":"filesize","type":"uint256"}],"name":"File_uploaded","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"customer","type":"address"},{"indexed":false,"internalType":"uint256","name":"balance","type":"uint256"}],"name":"Provided_proof","type":"event"},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"customers","outputs":[{"internalType":"uint256","name":"balance","type":"uint256"},{"internalType":"bytes32","name":"filehash","type":"bytes32"},{"internalType":"uint256","name":"filesize","type":"uint256"},{"internalType":"uint256","name":"last_reward","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"deposit","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[],"name":"endcontract","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"customer","type":"address"},{"internalType":"string","name":"file","type":"string"}],"name":"provideproof","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"string","name":"file","type":"string"}],"name":"uploadfile","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"customer","type":"address"},{"internalType":"string","name":"file","type":"string"}],"name":"verifyproof","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}]

const storageContract = web3 => {
    return new web3.eth.Contract(
        abi,
        "0x26c484Ae269aD089c68cd7F0d85f1D36e04409bc"
    )
}

export default storageContract